### Importing Libraries & API Configuration

In [ ]:
import os
import time
import requests
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

API_KEY = os.environ.get("SECTORS_API_KEY", "")

BASE_URL = "https://api.sectors.app/v2"
HEADERS = {"Authorization": API_KEY}

if not API_KEY:
    raise ValueError("SECTORS_API_KEY not yet set")
print("API Key & Library ready")

API Key & Library ready

### Date Parameters & Cache Folder Setup

In [13]:
END_DATE = datetime.now().strftime("%Y-%m-%d")
START_DATE = (datetime.now() - timedelta(days=180)).strftime("%Y-%m-%d")

CACHE_DIR = "cache/daily"
MANIFEST_PATH = "cache/fetch_manifest.csv"
UNIVERSE_PATH = "cache/universe_tickers.csv"
MARKET_CAP_RAW_PATH = "cache/market_cap_raw.csv"

os.makedirs(CACHE_DIR, exist_ok=True)

print(f"Target period: {START_DATE} to {END_DATE} (180 days)")
print(f"Cache directory: {CACHE_DIR}")

Target period: 2026-03-15 to 2026-09-11 (180 days)
Cache directory: cache/daily

### Micro + Small-Cap Universe Determination Function (Part A)

In [16]:
def fetch_all_market_caps(chunk_size: int = 200) -> list[dict]:
    all_rows = []
    offset = 0
    while True:
        params = {
            "where": "market_cap > 0",
            "order_by": "-market_cap",
            "limit": chunk_size,
            "offset": offset,
            "include_query_values": "true",
        }
        resp = requests.get(f"{BASE_URL}/companies/", headers=HEADERS, params=params, timeout=20)
        resp.raise_for_status()
        payload = resp.json()
        results = payload.get("results", [])
        if not results:
            break
        for r in results:
            qv = r.get("query_values") or {}
            mc = qv.get("market_cap") or r.get("market_cap")
            all_rows.append({
                "symbol": r.get("symbol"),
                "company_name": r.get("company_name"),
                "market_cap": mc,
            })
        pagination = payload.get("pagination", {})
        if not pagination.get("has_next"):
            break
        offset = pagination.get("next_offset", offset + chunk_size)
    return all_rows


def determine_universe() -> tuple[list[str], pd.DataFrame]:
    if os.path.exists(UNIVERSE_PATH):
        print(f"Universe loaded from cache: {UNIVERSE_PATH}")
        df = pd.read_csv(UNIVERSE_PATH)
        return df["symbol"].tolist(), df

    print("Fetching market cap data for all IDX stocks")
    rows = fetch_all_market_caps()
    raw_df = pd.DataFrame(rows)
    raw_df.to_csv(MARKET_CAP_RAW_PATH, index=False)

    caps = raw_df["market_cap"].dropna().astype(float)
    log_caps = np.log10(caps[caps > 0])
    q1, q2, q3 = np.percentile(log_caps, [25, 50, 75])
    small_cap_max = 10 ** q2

    print(f"Total stocks with market cap data: {len(caps)}")
    print(f"Small-cap upper limit (median log-market-cap): Rp {small_cap_max:,.0f}")

    universe_df = raw_df[
        raw_df["market_cap"].notna() & (raw_df["market_cap"] <= small_cap_max)
    ].copy()

    universe_df["symbol"] = universe_df["symbol"].str.replace(".JK", "", regex=False)
    universe_df.to_csv(UNIVERSE_PATH, index=False)

    print(f"Micro+small-cap universe: {len(universe_df)} stocks saved to {UNIVERSE_PATH}")
    return universe_df["symbol"].tolist(), universe_df

### Universe Definition Execution

In [17]:
universe_tickers, universe_df = determine_universe()
universe_df.head()

Universe loaded from cache: cache/universe_tickers.csv

  symbol                   company_name     market_cap
0   ADCP  PT Adhi Commuter Properti Tbk  1111111110000
1   HOME    Hotel Mandarine Regency Tbk  1110609739100
2   GDST     Gunawan Dianjaya Steel Tbk  1109100000000
3   PPRE              PT PP Presisi Tbk  1104221268000
4   VERN   PT Verona Indah Pictures Tbk  1096099082090

### Smart Extend & Retry 429 Helper (Part B)

In [18]:
def load_manifest() -> pd.DataFrame:
    if os.path.exists(MANIFEST_PATH):
        return pd.read_csv(MANIFEST_PATH)
    return pd.DataFrame(columns=["symbol", "status", "n_rows", "last_attempt"])

def save_manifest(df: pd.DataFrame) -> None:
    df.to_csv(MANIFEST_PATH, index=False)

def fetch_chunk_with_retry(ticker: str, start: str, end: str, max_retries: int = 5):
    for attempt in range(max_retries):
        try:
            resp = requests.get(
                f"{BASE_URL}/daily/{ticker}/",
                headers=HEADERS,
                params={"start": start, "end": end},
                timeout=20,
            )
            if resp.status_code == 200:
                return pd.DataFrame(resp.json())
            if resp.status_code == 429:
                wait = 2 ** attempt  # 1, 2, 4, 8, 16 detik
                print(f"[429: wait {wait}s] ", end="", flush=True)
                time.sleep(wait)
                continue
            return None
        except requests.exceptions.RequestException:
            time.sleep(1)
            continue
    return None

def extend_ticker_to_full_range(ticker: str, manifest: pd.DataFrame) -> pd.DataFrame:
    cache_path = os.path.join(CACHE_DIR, f"{ticker}.csv")

    if os.path.exists(cache_path):
        existing = pd.read_csv(cache_path)
        existing["date"] = pd.to_datetime(existing["date"])
        earliest_cached = existing["date"].min()
    else:
        existing = pd.DataFrame()
        earliest_cached = pd.to_datetime(END_DATE)

    target_start = pd.to_datetime(START_DATE)

    if earliest_cached <= target_start:
        return existing

    missing_end = (earliest_cached - timedelta(days=1)).strftime("%Y-%m-%d")
    df_new = fetch_chunk_with_retry(ticker, START_DATE, missing_end)

    if df_new is None:
        manifest = manifest[manifest["symbol"] != ticker]
        manifest = pd.concat([manifest, pd.DataFrame([{
            "symbol": ticker, "status": "extend_failed",
            "n_rows": len(existing), "last_attempt": pd.Timestamp.now(),
        }])], ignore_index=True)
        save_manifest(manifest)
        return existing

    if not df_new.empty:
        df_new["date"] = pd.to_datetime(df_new["date"])

    combined = pd.concat([existing, df_new], ignore_index=True)
    combined = combined.drop_duplicates(subset=["date"]).sort_values("date")
    combined.to_csv(cache_path, index=False)

    manifest = manifest[manifest["symbol"] != ticker]
    manifest = pd.concat([manifest, pd.DataFrame([{
        "symbol": ticker, "status": "done",
        "n_rows": len(combined), "last_attempt": pd.Timestamp.now(),
    }])], ignore_index=True)
    save_manifest(manifest)

    return combined

### Implementation of Cache Extension to 180 Days

In [19]:
print(f"Extending cache for {len(universe_tickers)} stocks to the range {START_DATE} to {END_DATE}")

manifest = load_manifest()
all_results = []
n_skipped = 0
n_extended = 0

for i, ticker in enumerate(universe_tickers):
    before = os.path.exists(os.path.join(CACHE_DIR, f"{ticker}.csv"))
    df = extend_ticker_to_full_range(ticker, manifest)
    manifest = load_manifest()

    min_date = df["date"].min() if not df.empty else None
    already_full = before and min_date is not None and pd.to_datetime(min_date) <= pd.to_datetime(START_DATE)

    if already_full:
        n_skipped += 1
        tag = "SKIP"
    else:
        n_extended += 1
        tag = "EXTENDED"
        time.sleep(0.5)

    print(f"  [{i + 1:3d}/{len(universe_tickers)}] {ticker:<8} {tag} ({len(df)} baris)")

    if not df.empty:
        df = df.copy()
        df["symbol"] = ticker
        all_results.append(df)

if all_results:
    combined = pd.concat(all_results, ignore_index=True)
    combined.to_csv("cache/daily_all_combined.csv", index=False)
    print(f"\nDone! {combined['symbol'].nunique()} stocks, {len(combined)} rows")
    print(f"Combined date range: {combined['date'].min()} to {combined['date'].max()}")
    print(f"Summary: {n_extended} extended, {n_skipped} skipped")

Extending cache for 481 stocks to the range 2026-03-15 to 2026-09-11
  [  1/481] ADCP     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [  2/481] HOME     EXTENDED (114 baris)
  [  3/481] GDST     EXTENDED (114 baris)
  [  4/481] PPRE     EXTENDED (114 baris)
  [  5/481] VERN     EXTENDED (114 baris)
  [  6/481] BBLD     EXTENDED (114 baris)
  [  7/481] BBRM     EXTENDED (114 baris)
  [  8/481] AISA     EXTENDED (114 baris)
  [  9/481] ADMG     EXTENDED (114 baris)
  [ 10/481] JIHD     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 11/481] TAMU     EXTENDED (114 baris)
  [ 12/481] ARTA     EXTENDED (114 baris)
  [ 13/481] CITY     EXTENDED (114 baris)
  [ 14/481] PTPW     EXTENDED (114 baris)
  [ 15/481] TCID     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 16/481] KING     EXTENDED (114 baris)
  [ 17/481] CAMP     EXTENDED (114 baris)
  [ 18/481] BUDI     EXTENDED (114 baris)
  [ 19/481] WOMF     EXTENDED (114 baris)
  [ 20/481] RELI     EXTENDED (114 baris)
  [ 21/481] PDPP     EXTENDED (114 baris)
  [ 22/481] BUAH     EXTENDED (114 baris)
  [ 23/481] BSML     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 24/481] PPRO     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 25/481] MFMI     EXTENDED (114 baris)
  [ 26/481] VOKS     EXTENDED (114 baris)
  [ 27/481] PADI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 28/481] SOSS     EXTENDED (114 baris)
  [ 29/481] SHID     EXTENDED (114 baris)
  [ 30/481] TALF     EXTENDED (114 baris)
  [ 31/481] SKBM     EXTENDED (114 baris)
  [ 32/481] GHON     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s] [429: wait 16s]   [ 33/481] POLL     EXTENDED (61 baris)
  [ 34/481] SPMA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 35/481] WMPP     EXTENDED (114 baris)
  [ 36/481] FOLK     EXTENDED (114 baris)
  [ 37/481] RSGK     EXTENDED (62 baris)
  [ 38/481] TBMS     EXTENDED (114 baris)
  [ 39/481] AMAN     EXTENDED (114 baris)
  [ 40/481] HGII     EXTENDED (114 baris)
  [ 41/481] KSIX     EXTENDED (114 baris)
  [ 42/481] YPAS     EXTENDED (114 baris)
  [ 43/481] MOLI     EXTENDED (114 baris)
  [ 44/481] WIRG     EXTENDED (114 baris)
  [ 45/481] RODA     EXTENDED (114 baris)
  [ 46/481] RANC     EXTENDED (114 baris)
  [ 47/481] LIVE     EXTENDED (114 baris)
  [ 48/481] ASLC     EXTENDED (114 baris)
  [ 49/481] AREA     EXTENDED (114 baris)
  [ 50/481] GULA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 51/481] BLTA     EXTENDED (114 baris)
  [ 52/481] BELL     EXTENDED (114 baris)
  [ 53/481] INDO     EXTENDED (114 baris)
  [ 54/481] AMOR     EXTENDED (114 baris)
  [ 55/481] MITI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 56/481] HITS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 57/481] INRU     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 58/481] IBOS     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s]

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 59/481] WSBP     EXTENDED (114 baris)
  [ 60/481] MTWI     EXTENDED (114 baris)
  [ 61/481] SMGA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 62/481] MABA     EXTENDED (114 baris)
  [ 63/481] DGIK     EXTENDED (114 baris)
  [ 64/481] PIPA     EXTENDED (114 baris)
  [ 65/481] KDSI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 66/481] ZINC     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 67/481] VIVA     EXTENDED (114 baris)
  [ 68/481] IPOL     EXTENDED (114 baris)
  [ 69/481] PJAA     EXTENDED (114 baris)
  [ 70/481] BDKR     EXTENDED (114 baris)
  [ 71/481] APEX     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 72/481] CMPP     EXTENDED (114 baris)
  [ 73/481] JELI     EXTENDED (46 baris)
  [ 74/481] URBN     EXTENDED (114 baris)
  [ 75/481] SAFE     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 76/481] PTMR     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 77/481] PGJO     EXTENDED (114 baris)
  [ 78/481] WTON     EXTENDED (114 baris)
  [ 79/481] ATAP     EXTENDED (114 baris)
  [ 80/481] LABS     EXTENDED (114 baris)
  [ 81/481] PADA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 82/481] LFLO     EXTENDED (114 baris)
  [ 83/481] STRK     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s] [429: wait 16s]   [ 84/481] AXIO     EXTENDED (61 baris)
  [ 85/481] KONI     EXTENDED (114 baris)
  [ 86/481] CBPE     EXTENDED (114 baris)
  [ 87/481] HDFA     EXTENDED (114 baris)
  [ 88/481] LEAD     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 89/481] CHIP     EXTENDED (114 baris)
  [ 90/481] BPFI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 91/481] LUCY     EXTENDED (114 baris)
  [ 92/481] WMUU     EXTENDED (114 baris)
  [ 93/481] SWID     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [ 94/481] LCGP     EXTENDED (114 baris)
  [ 95/481] NIKL     EXTENDED (114 baris)
  [ 96/481] IKBI     EXTENDED (114 baris)
  [ 97/481] EMMI     EXTENDED (45 baris)
  [ 98/481] MDLN     EXTENDED (114 baris)
  [ 99/481] ZONE     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [100/481] SMRU     EXTENDED (114 baris)
  [101/481] BRNA     EXTENDED (114 baris)
  [102/481] SOTS     EXTENDED (114 baris)
  [103/481] SRSN     EXTENDED (114 baris)
  [104/481] KOKA     EXTENDED (114 baris)
  [105/481] ZATA     EXTENDED (114 baris)
  [106/481] FITT     EXTENDED (114 baris)
  [107/481] IRRA     EXTENDED (114 baris)
  [108/481] BABY     EXTENDED (114 baris)
  [109/481] PMUI     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s]

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [110/481] PBRX     EXTENDED (114 baris)
  [111/481] PZZA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [112/481] TIRT     EXTENDED (114 baris)
  [113/481] PANR     EXTENDED (114 baris)
  [114/481] DPUM     EXTENDED (114 baris)
  [115/481] SSTM     EXTENDED (114 baris)
  [116/481] SULI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [117/481] SOFA     EXTENDED (114 baris)
  [118/481] BAJA     EXTENDED (114 baris)
  [119/481] RMKO     EXTENDED (114 baris)
  [120/481] VRNA     EXTENDED (114 baris)
  [121/481] UNTD     EXTENDED (114 baris)
  [122/481] IDPR     EXTENDED (114 baris)
  [123/481] AWAN     EXTENDED (114 baris)
  [124/481] GUNA     EXTENDED (114 baris)
  [125/481] PEVE     EXTENDED (114 baris)
  [126/481] TRIS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [127/481] CASH     EXTENDED (114 baris)
  [128/481] ELIT     EXTENDED (114 baris)
  [129/481] CHEK     EXTENDED (114 baris)
  [130/481] KOCI     EXTENDED (114 baris)
  [131/481] MHKI     EXTENDED (114 baris)
  [132/481] SMKL     EXTENDED (114 baris)
  [133/481] HOKI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [134/481] INPS     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s] [429: wait 16s]   [135/481] SURI     EXTENDED (61 baris)
  [136/481] KDTN     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [137/481] BTEK     EXTENDED (114 baris)
  [138/481] MDKI     EXTENDED (114 baris)
  [139/481] DART     EXTENDED (114 baris)
  [140/481] PEGE     EXTENDED (114 baris)
  [141/481] CLPI     EXTENDED (114 baris)
  [142/481] JECC     EXTENDED (114 baris)
  [143/481] ENAK     EXTENDED (114 baris)
  [144/481] NELY     EXTENDED (114 baris)
  [145/481] WEGE     EXTENDED (114 baris)
  [146/481] HAIS     EXTENDED (114 baris)
  [147/481] VTNY     EXTENDED (114 baris)
  [148/481] AHAP     EXTENDED (114 baris)
  [149/481] GLVA     EXTENDED (114 baris)
  [150/481] BOAT     EXTENDED (114 baris)
  [151/481] GTRA     EXTENDED (114 baris)
  [152/481] MAXI     EXTENDED (114 baris)
  [153/481] BAYU     EXTENDED (114 baris)
  [154/481] HYGN     EXTENDED (114 baris)
  [155/481] MREI     EXTENDED (114 baris)
  [156/481] HALO     EXTENDED (114 baris)
  [157/481] TRUK     EXTENDED (114 baris)
  [158/481] GDYR     EXTENDED (114 baris)
  [159/481] BBSS     EXTENDED (114 baris)
  [160/481] HOPE     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s]   [161/481] SMLE     EXTENDED (114 baris)
  [162/481] GPRA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [163/481] ARMY     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [164/481] MAGP     EXTENDED (114 baris)
  [165/481] IGAR     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [166/481] KBRI     EXTENDED (114 baris)
  [167/481] PRDL     EXTENDED (43 baris)
  [168/481] RIGS     EXTENDED (114 baris)
  [169/481] UFOE     EXTENDED (114 baris)
  [170/481] CRAB     EXTENDED (114 baris)
  [171/481] ESTA     EXTENDED (114 baris)
  [172/481] NZIA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [173/481] POSA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [174/481] MTFN     EXTENDED (114 baris)
  [175/481] KMDS     EXTENDED (114 baris)
  [176/481] PRIM     EXTENDED (114 baris)
  [177/481] KOBX     EXTENDED (114 baris)
  [178/481] HOMI     EXTENDED (114 baris)
  [179/481] MUTU     EXTENDED (114 baris)
  [180/481] CRSN     EXTENDED (114 baris)
  [181/481] ESTI     EXTENDED (114 baris)
  [182/481] TYRE     EXTENDED (114 baris)
  [183/481] PNSE     EXTENDED (114 baris)
  [184/481] ASPR     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [185/481] INAF     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s]   [186/481] SCNP     EXTENDED (114 baris)
  [187/481] CSIS     EXTENDED (114 baris)
  [188/481] UNIQ     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [189/481] NUSA     EXTENDED (114 baris)
  [190/481] DGNS     EXTENDED (114 baris)
  [191/481] APLI     EXTENDED (114 baris)
  [192/481] CCSI     EXTENDED (114 baris)
  [193/481] GTBO     EXTENDED (114 baris)
  [194/481] KBLM     EXTENDED (114 baris)
  [195/481] TRUE     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [196/481] NASA     EXTENDED (114 baris)
  [197/481] TOSK     EXTENDED (114 baris)
  [198/481] DYAN     EXTENDED (114 baris)
  [199/481] DADA     EXTENDED (114 baris)
  [200/481] EAST     EXTENDED (114 baris)
  [201/481] BMSR     EXTENDED (114 baris)
  [202/481] JATI     EXTENDED (114 baris)
  [203/481] WINE     EXTENDED (114 baris)
  [204/481] ASRM     EXTENDED (114 baris)
  [205/481] GOLD     EXTENDED (114 baris)
  [206/481] PTPS     EXTENDED (114 baris)
  [207/481] PJHB     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [208/481] PPGL     EXTENDED (114 baris)
  [209/481] TRUS     EXTENDED (114 baris)
  [210/481] IOTF     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s] [429: wait 16s]   [211/481] BIPP     EXTENDED (61 baris)
  [212/481] SATU     EXTENDED (114 baris)
  [213/481] VAST     EXTENDED (114 baris)
  [214/481] MGNA     EXTENDED (114 baris)
  [215/481] ASPI     EXTENDED (114 baris)
  [216/481] MPXL     EXTENDED (114 baris)
  [217/481] MICE     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [218/481] HBAT     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [219/481] TARA     EXTENDED (114 baris)
  [220/481] REAL     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [221/481] CNKO     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [222/481] ETWA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [223/481] WGSH     EXTENDED (114 baris)
  [224/481] AKPI     EXTENDED (114 baris)
  [225/481] FUJI     EXTENDED (114 baris)
  [226/481] UVCR     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [227/481] KBAG     EXTENDED (114 baris)
  [228/481] IKPM     EXTENDED (114 baris)
  [229/481] BEER     EXTENDED (114 baris)
  [230/481] NAIK     EXTENDED (114 baris)
  [231/481] YOII     EXTENDED (114 baris)
  [232/481] DEWI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [233/481] MYTX     EXTENDED (114 baris)
  [234/481] KLAS     EXTENDED (114 baris)
  [235/481] TFAS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [236/481] KIAS     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s]   [237/481] ATLA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [238/481] MEJA     EXTENDED (114 baris)
  [239/481] TRON     EXTENDED (114 baris)
  [240/481] SOLA     EXTENDED (114 baris)
  [241/481] BAIK     EXTENDED (114 baris)
  [242/481] ASHA     EXTENDED (114 baris)
  [243/481] PART     EXTENDED (114 baris)
  [244/481] DOSS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [245/481] WICO     EXTENDED (114 baris)
  [246/481] OKAS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [247/481] TGUK     EXTENDED (114 baris)
  [248/481] BATR     EXTENDED (114 baris)
  [249/481] LPLI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [250/481] ALMI     EXTENDED (114 baris)
  [251/481] LAPD     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [252/481] HAJJ     EXTENDED (114 baris)
  [253/481] PTSP     EXTENDED (114 baris)
  [254/481] EMDE     EXTENDED (114 baris)
  [255/481] PDES     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [256/481] HRME     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [257/481] SAGE     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [258/481] KREN     EXTENDED (114 baris)
  [259/481] BINO     EXTENDED (114 baris)
  [260/481] SAPX     EXTENDED (114 baris)
  [261/481] POLA     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s]   [262/481] CGAS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [263/481] IKAI     EXTENDED (114 baris)
  [264/481] AMIN     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [265/481] GRPM     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [266/481] AMMS     EXTENDED (114 baris)
  [267/481] BPTR     EXTENDED (114 baris)
  [268/481] BTON     EXTENDED (114 baris)
  [269/481] PEHA     EXTENDED (114 baris)
  [270/481] MCAS     EXTENDED (114 baris)
  [271/481] SDPC     EXTENDED (114 baris)
  [272/481] INOV     EXTENDED (114 baris)
  [273/481] BOBA     EXTENDED (114 baris)
  [274/481] TIRA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [275/481] AKKU     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [276/481] COWL     EXTENDED (114 baris)
  [277/481] ERTX     EXTENDED (114 baris)
  [278/481] TAMA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [279/481] HILL     EXTENDED (114 baris)
  [280/481] NTBK     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [281/481] RELF     EXTENDED (114 baris)
  [282/481] ACRO     EXTENDED (114 baris)
  [283/481] KBLV     EXTENDED (114 baris)
  [284/481] ECII     EXTENDED (114 baris)
  [285/481] JMAS     EXTENDED (114 baris)
  [286/481] ASJT     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s] [429: wait 16s]   [287/481] AKSI     EXTENDED (61 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [288/481] DUCK     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [289/481] BEBS     EXTENDED (114 baris)
  [290/481] VINS     EXTENDED (114 baris)
  [291/481] SLIS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [292/481] ANDI     EXTENDED (114 baris)
  [293/481] LAND     EXTENDED (114 baris)
  [294/481] LPPS     EXTENDED (114 baris)
  [295/481] WAPO     EXTENDED (114 baris)
  [296/481] ITIC     EXTENDED (114 baris)
  [297/481] PSDN     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [298/481] NINE     EXTENDED (114 baris)
  [299/481] GPSO     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [300/481] PURA     EXTENDED (114 baris)
  [301/481] APII     EXTENDED (114 baris)
  [302/481] KAQI     EXTENDED (114 baris)
  [303/481] SDMU     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [304/481] INTA     EXTENDED (114 baris)
  [305/481] PTMP     EXTENDED (114 baris)
  [306/481] PPRI     EXTENDED (114 baris)
  [307/481] DIVA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [308/481] MSIE     EXTENDED (114 baris)
  [309/481] LION     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [310/481] MDRN     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [311/481] BAUT     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [312/481] NAYZ     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s]   [313/481] TRJA     EXTENDED (114 baris)
  [314/481] ASDM     EXTENDED (114 baris)
  [315/481] YELO     EXTENDED (114 baris)
  [316/481] COAL     EXTENDED (114 baris)
  [317/481] FIRE     EXTENDED (114 baris)
  [318/481] EPAC     EXTENDED (114 baris)
  [319/481] CAKK     EXTENDED (114 baris)
  [320/481] NPGF     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [321/481] MTRA     EXTENDED (114 baris)
  [322/481] CINT     EXTENDED (114 baris)
  [323/481] DKHH     EXTENDED (114 baris)
  [324/481] LPIN     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [325/481] GOLL     EXTENDED (114 baris)
  [326/481] MPIX     EXTENDED (114 baris)
  [327/481] PAMG     EXTENDED (114 baris)
  [328/481] PUDP     EXTENDED (114 baris)
  [329/481] FWCT     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [330/481] GAMA     EXTENDED (114 baris)
  [331/481] TMPO     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [332/481] HOTL     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [333/481] IPAC     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [334/481] GLOB     EXTENDED (114 baris)
  [335/481] RGAS     EXTENDED (114 baris)
  [336/481] ZYRX     EXTENDED (114 baris)
  [337/481] HELI     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s] [429: wait 16s]   [338/481] MTPS     EXTENDED (61 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [339/481] MANG     EXTENDED (114 baris)
  [340/481] OBAT     EXTENDED (114 baris)
  [341/481] RBMS     EXTENDED (114 baris)
  [342/481] INCI     EXTENDED (114 baris)
  [343/481] DSFI     EXTENDED (114 baris)
  [344/481] LMPI     EXTENDED (114 baris)
  [345/481] MRAT     EXTENDED (114 baris)
  [346/481] WEHA     EXTENDED (114 baris)
  [347/481] SEMA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [348/481] WINR     EXTENDED (114 baris)
  [349/481] ICON     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [350/481] HKMU     EXTENDED (114 baris)
  [351/481] INTD     EXTENDED (114 baris)
  [352/481] RUIS     EXTENDED (114 baris)
  [353/481] ENZO     EXTENDED (114 baris)
  [354/481] DFAM     EXTENDED (114 baris)
  [355/481] LAJU     EXTENDED (114 baris)
  [356/481] OBMD     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [357/481] NANO     EXTENDED (114 baris)
  [358/481] CTTH     EXTENDED (114 baris)
  [359/481] PURI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [360/481] ASMI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [361/481] KLIN     EXTENDED (114 baris)
  [362/481] LABA     EXTENDED (114 baris)
  [363/481] MBTO     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s]   [364/481] GEMA     EXTENDED (114 baris)
  [365/481] CSMI     EXTENDED (114 baris)
  [366/481] TOOL     EXTENDED (114 baris)
  [367/481] PTIS     EXTENDED (114 baris)
  [368/481] KOPI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [369/481] KKES     EXTENDED (114 baris)
  [370/481] MEDS     EXTENDED (114 baris)
  [371/481] WOWS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [372/481] TAXI     EXTENDED (114 baris)
  [373/481] ESIP     EXTENDED (114 baris)
  [374/481] ASBI     EXTENDED (114 baris)
  [375/481] AYLS     EXTENDED (114 baris)
  [376/481] GRPH     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [377/481] SMKM     EXTENDED (114 baris)
  [378/481] OILS     EXTENDED (114 baris)
  [379/481] JAYA     EXTENDED (114 baris)
  [380/481] MSKY     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [381/481] OLIV     EXTENDED (114 baris)
  [382/481] NASI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [383/481] PMMP     EXTENDED (114 baris)
  [384/481] KUAS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [385/481] BAPI     EXTENDED (114 baris)
  [386/481] MERI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [387/481] ZBRA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [388/481] KARW     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s] [429: wait 16s]   [389/481] CHEM     EXTENDED (61 baris)
  [390/481] ISEA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [391/481] CPRI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [392/481] MARI     EXTENDED (114 baris)
  [393/481] OPMS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [394/481] ABBA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [395/481] POOL     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [396/481] MTSM     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [397/481] FOOD     EXTENDED (114 baris)
  [398/481] INAI     EXTENDED (114 baris)
  [399/481] KRYA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [400/481] RAFI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [401/481] CANI     EXTENDED (114 baris)
  [402/481] AIMS     EXTENDED (114 baris)
  [403/481] PICO     EXTENDED (114 baris)
  [404/481] LCKM     EXTENDED (114 baris)
  [405/481] KIOS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [406/481] ISAP     EXTENDED (114 baris)
  [407/481] SICO     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [408/481] JSKY     EXTENDED (114 baris)
  [409/481] JAST     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [410/481] PTDU     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [411/481] FLMC     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [412/481] SCPI     EXTENDED (114 baris)
  [413/481] SNLK     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [414/481] DPNS     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s]   [415/481] SBMA     EXTENDED (114 baris)
  [416/481] PGLI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [417/481] MIRA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [418/481] IBFN     EXTENDED (114 baris)
  [419/481] MPOW     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [420/481] CBMF     EXTENDED (114 baris)
  [421/481] BAPA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [422/481] RCCC     EXTENDED (114 baris)
  [423/481] BCIP     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [424/481] ENVY     EXTENDED (114 baris)
  [425/481] LUCK     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [426/481] SPRE     EXTENDED (114 baris)
  [427/481] KJEN     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [428/481] POLY     EXTENDED (114 baris)
  [429/481] IKAN     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [430/481] BATA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [431/481] KOIN     EXTENDED (114 baris)
  [432/481] HDIT     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [433/481] MENN     EXTENDED (114 baris)
  [434/481] TNCA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [435/481] RUNS     EXTENDED (114 baris)
  [436/481] BRRC     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [437/481] TGRA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [438/481] LMAX     EXTENDED (114 baris)
  [439/481] KICI     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s] [429: wait 16s]   [440/481] DEFI     EXTENDED (61 baris)
  [441/481] LRNA     EXTENDED (114 baris)
  [442/481] INCF     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [443/481] PLAN     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [444/481] PURE     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [445/481] BOSS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [446/481] IDEA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [447/481] LOPI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [448/481] TELE     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [449/481] IPPE     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [450/481] TECH     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [451/481] TRIL     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [452/481] PLAS     EXTENDED (114 baris)
  [453/481] TAYS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [454/481] AEGS     EXTENDED (114 baris)
  [455/481] RICY     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [456/481] PCAR     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [457/481] HADE     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [458/481] BIMA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [459/481] SWAT     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [460/481] DIGI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [461/481] WIDI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [462/481] ARKA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [463/481] OCAP     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [464/481] SOUL     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [465/481] ALTO     EXTENDED (114 baris)
[429: wait 1s] [429: wait 2s] [429: wait 4s] [429: wait 8s]

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [466/481] LMAS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [467/481] BMBL     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [468/481] TOPS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [469/481] BIKA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [470/481] SKYB     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [471/481] FIMP     EXTENDED (114 baris)
  [472/481] INDX     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [473/481] LMSH     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [474/481] UNIT     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [475/481] SIMA     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [476/481] ARTI     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [477/481] KAYU     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [478/481] TOYS     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [479/481] DEAL     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [480/481] MKNT     EXTENDED (114 baris)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23080\2242971189.py:62: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([existing, df_new], ignore_index=True)

  [481/481] SBAT     EXTENDED (114 baris)

Done! 481 stocks, 54150 rows
Combined date range: 2026-03-16 00:00:00 to 2026-09-10 00:00:00
Summary: 481 extended, 0 skipped

### Validation of 180-Day Final Result Data

In [20]:
df_daily = pd.read_csv("cache/daily_all_combined.csv")

print(f"Total Unique Stocks : {df_daily['symbol'].nunique()}")
print(f"Total Data Rows : {len(df_daily):,}")
print(f"Date Range : {df_daily['date'].min()} to {df_daily['date'].max()}")
print(f"Average rows per stock: {len(df_daily) / df_daily['symbol'].nunique():.0f} trading days")

df_daily.head()

Total Unique Stocks : 481
Total Data Rows : 54,150
Date Range : 2026-03-16 to 2026-09-10
Average rows per stock: 113 trading days

  symbol        date  close  open  high  low   volume     market_cap
0   ADCP  2026-03-16     50  50.0    51   50  1280400  1111111110000
1   ADCP  2026-03-17     50  50.0    51   50  2432700  1111111110000
2   ADCP  2026-03-25     50  50.0    51   50  1218200  1111111110000
3   ADCP  2026-03-26     50  50.0    51   50  3241300  1111111110000
4   ADCP  2026-03-27     50  50.0    51   50   858500  1111111110000